---
archives:
  - format_overrides:
      - goos: windows
        format: zip
before:
  hooks:
    - go mod tidy -compat=1.17
builds:
  - main: ./cmd/rom/main.go
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - darwin
      - linux
      - windows
checksum:
  name_template: 'checksums.txt'
release:
  prerelease: auto
changelog:
  use: github-native
